# Generated by Django 3.0.5 on 2021-02-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
