# Generated by Django 3.0.5 on 2020-04-20 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200419_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.Post'),
        ),
    ]
