# Generated by Django 3.0.5 on 2020-04-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200423_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
