# Generated by Django 3.0.5 on 2020-04-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_comments_message'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='likes',
            constraint=models.UniqueConstraint(fields=('post_id', 'user_id'), name='like object can only be one'),
        ),
    ]
