# Generated by Django 3.0.5 on 2020-04-25 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0011_auto_20200425_0603'),
        ('api', '0009_remove_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='api_auth.Constituency'),
        ),
    ]
