# Generated by Django 3.0.5 on 2020-05-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200425_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file_type',
            field=models.IntegerField(blank=True, choices=[(1, 'IMG'), (2, 'VID'), (3, 'OTHER')], null=True),
        ),
    ]
