# Generated by Django 3.0.5 on 2020-05-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_attachment_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='attachment_key',
            field=models.TextField(blank=True),
        ),
    ]
