# Generated by Django 3.0.5 on 2020-05-14 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0013_userprofile_dob'),
        ('api', '0012_attachment_attachment_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='api_auth.District'),
        ),
    ]
