# Generated by Django 3.0.5 on 2020-05-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_post_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='attachment_key',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='attachment_url',
        ),
        migrations.AddField(
            model_name='attachment',
            name='attachment',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
