# Generated by Django 3.0.5 on 2020-07-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200728_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.IntegerField(choices=[(1, 'political'), (2, 'medical'), (3, 'problem'), (4, 'feed')]),
        ),
    ]
