# Generated by Django 3.0.5 on 2020-09-22 16:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_auto_20200825_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tagged_users',
            field=models.ManyToManyField(null=True, related_name='tagged', to=settings.AUTH_USER_MODEL),
        ),
    ]
