# Generated by Django 3.0.5 on 2020-09-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_auto_20200908_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
