# Generated by Django 3.0.5 on 2020-09-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20200908_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='media_type',
            field=models.IntegerField(choices=[(1, 'IMG'), (2, 'VID'), (3, 'OTHER')]),
        ),
    ]
