# Generated by Django 3.0.5 on 2020-09-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_auto_20200908_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='story_type',
        ),
        migrations.AlterField(
            model_name='story',
            name='media_type',
            field=models.IntegerField(choices=[(1, 'IMG'), (2, 'VID'), (3, 'TEXT'), (4, 'OTHER')]),
        ),
    ]
