# Generated by Django 3.0.5 on 2023-09-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketattachments',
            name='attachment',
            field=models.FileField(blank=True, upload_to='attechment'),
        ),
    ]
