# Generated by Django 3.0.5 on 2020-08-27 17:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PoolAnswer',
            new_name='PollAnswer',
        ),
    ]
