# Generated by Django 3.0.5 on 2020-04-19 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0003_auto_20200418_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='constituency',
            name='district_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constituencies', to='api_auth.District'),
        ),
        migrations.AlterField(
            model_name='district',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='api_auth.State'),
        ),
        migrations.AlterField(
            model_name='state',
            name='country_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='api_auth.Country'),
        ),
    ]
