# Generated by Django 3.0.5 on 2020-04-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0004_auto_20200419_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='medical_rep',
        ),
        migrations.RemoveField(
            model_name='user',
            name='political_rep',
        ),
    ]
