# Generated by Django 3.0.5 on 2020-04-24 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0008_auto_20200424_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='constituency_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='api_auth.Constituency'),
        ),
    ]
