# Generated by Django 3.0.5 on 2020-04-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0009_auto_20200424_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Trans-Sexual')], null=True),
        ),
    ]
