# Generated by Django 3.0.5 on 2020-05-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0011_auto_20200425_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.SmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'private')], default=3),
        ),
    ]
