# Generated by Django 3.0.5 on 2020-05-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0012_auto_20200506_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dob',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
