# Generated by Django 3.0.5 on 2020-05-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0013_userprofile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_create',
            field=models.BooleanField(default=True),
        ),
    ]
