# Generated by Django 3.0.5 on 2020-05-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0017_auto_20200522_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='profile_pictures_dev'),
        ),
    ]
