# Generated by Django 3.0.5 on 2020-05-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0018_auto_20200527_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='anonymous_avatar',
            field=models.ImageField(blank=True, default='attachments/icons/incognito/incognito9.png', upload_to='profile_pictures_dev'),
        ),
    ]
