# Generated by Django 3.0.5 on 2020-06-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0019_userprofile_anonymous_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
