# Generated by Django 3.0.5 on 2020-07-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0020_user_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
    ]
