# Generated by Django 3.0.5 on 2020-07-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0021_auto_20200719_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='foreign_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='anonymous_avatar',
            field=models.ImageField(blank=True, default='icons/incognito/incognito9.png', upload_to='profile_pictures'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='profile_pictures'),
        ),
    ]
