# Generated by Django 3.0.5 on 2020-08-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0023_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
