# Generated by Django 3.0.5 on 2020-08-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0024_auto_20200805_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
