# Generated by Django 3.0.5 on 2020-08-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0026_auto_20200813_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='anonymous_avatar',
            field=models.ImageField(blank=True, default='user_avatars/hide.gif', upload_to='profile_pictures'),
        ),
    ]
