# Generated by Django 3.0.5 on 2020-12-29 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0027_auto_20200814_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='constituency_id',
        ),
    ]
