# Generated by Django 3.0.5 on 2021-02-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0029_auto_20210122_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
