# Generated by Django 3.0.5 on 2023-09-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0030_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='anonymous_avatar',
            field=models.ImageField(blank=True, default='user_avatars/hide.gif', upload_to='attechment'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='attechment'),
        ),
    ]
