# Generated by Django 3.0.5 on 2020-06-19 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20200614_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.Group'),
        ),
    ]
