# Generated by Django 3.0.5 on 2020-06-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20200619_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='attachments_dev/group_pictures_dev'),
        ),
        migrations.AddField(
            model_name='group',
            name='multitenant',
            field=models.BooleanField(default=True),
        ),
    ]
