# Generated by Django 3.0.5 on 2023-09-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_auto_20200728_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='attechment'),
        ),
    ]
