# Generated by Django 3.0.5 on 2021-01-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20201004_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'Follow'), (2, 'Tag'), (3, 'Like'), (4, 'Comment')]),
        ),
    ]
